name: lave CI wath Gradle

on:
 pull_request:
    branches: [ "main" ]
 push:
   branches: [ "main" ]

jobs:
 build-test:
   name: Complle and test applicatIon

   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
         java-version: '21'
         distribution: 'temurin'
  
      - name: Build
        run: make build
  
      - name: Test run
        id: test
        run: make test
